FROM resin/raspberry-pi2-node:10-slim

RUN [ "cross-build-start" ]

RUN apt-get update
RUN apt-get install -y git
#RUN apt-get install -y python
#RUN apt-get install -y make
RUN apt-get clean

RUN [ "cross-build-end" ]

COPY npg.sh npg.sh
CMD ./npg.sh